export const countries = {
    netherlands: 'Netherlands',
    belgium: 'Belgium',
    germany: 'Germany',
    austria: 'Austria',
    bulgaria: 'Bulgaria',
    croatia: 'Croatia',
    cyprus: 'Cyprus',
    czechrepublic: 'Czech Republic',
    denmark: 'Denmark',
    estonia: 'Estonia',
    finland: 'Finland',
    france: 'France',
    greece: 'Greece',
    hungary: 'Hungary',
    ireland: 'Ireland',
    italy: 'Italy',
    latvia: 'Latvia',
    lithuania: 'Lithuania',
    luxembourg: 'Luxembourg',
    malta: 'Malta',
    poland: 'Poland',
    portugal: 'Portugal',
    romania: 'Romania',
    slovakia: 'Slovakia',
    slovenia: 'Slovenia',
    spain: 'Spain',
    sweden: 'Sweden',
  }