import React from 'react';
export const countries = {
  nl: 'Netherlands',
  de: 'Germany',
  fr: 'France',
  es: 'Spain',
  ie: 'Ireland',
  be: 'Belgium',
  it: 'Italy',
  lu: 'Luxembourg',
  at: 'Austria',
  pl: 'Poland',
  hu: 'Hungary',
  gr: 'Greece',
  ro: 'Romania',
  bg: 'Bulgaria',
  ee: 'Estonia',
  lt: 'Lithuania',
  lv: 'Latvia',
  dk: 'Denmark',
  fi: 'Finland',
  se: 'Sweden',
  pt: 'Portugal',
  cy: 'Cyprus',
  cz: 'Czech Republic',
  sk: 'Slovakia',
  si: 'Slovenia',
  hr: 'Croatia',
  mt: 'Malta'
};